apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hello-world-app
  template:
    metadata:
      labels:
        app: java-hello-world-app
    spec:
      containers:
        - name: java-hello-world-app
          image: your-docker-image:latest  # Replace with your Docker image name and tag
          ports:
            - containerPort: 8080

