apiVersion: v1
kind: Service
metadata:
  name: java-hello-world-service
spec:
  selector:
    app: java-hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use NodePort or ClusterIP based on your requirements

